# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-added-large-files
        args: ["--maxkb=250"]
        exclude: ^(docs/visualizations/.*|uv\.lock)$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        stages: [pre-commit]
        exclude: '.*\.(lock|ipynb)$'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.8.3"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.0.0, types-toml, types-pyyaml]
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.10
    hooks:
      - id: typos
        exclude: constants\.py$
  - repo: local
    hooks:
      - id: tests
        name: tests
        stages: [pre-push]
        language: system
        entry: uv run pytest
        types: [python]
        pass_filenames: false
