[default.extend-words]
# Elements
Ba = "Ba"
Nd = "Nd"
ND = "ND"

[files]
extend-exclude = [
    "docs/visualizations/programoutputs.ipynb",
    "docs/visualizations/U1-_mmff94s_180-opt-terachem-thf.json",
]
